
version: "3"
services:
  back:
    container_name: back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3031:3031"
    restart: always
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./initdump.sql:/docker-entrypoint-initdb.d/dump.sql